import { Link } from '@remix-run/react';
import programmer from '~/images/programmer.png';

export default function Index() {
  return (
    <>
      <section className='flex flex-col items-center space-y-2 md:flex-row-reverse'>
        <img
          src={programmer}
          alt='progammer sketch'
          className='w-3/4 h-auto md:w-1/2'
          title='Art generated by https://midjourney.com/'
        />
        <div className='text-center space-y-4 md:text-left md:space-y-8'>
          <h1 className='font-merriweather text-4xl font-bold md:text-6xl'>
            Diego Vazquez
          </h1>
          <p className='font-lato text-lg text-center md:text-2xl md:text-left'>
            Software Engineer very passionate about creating compelling
            solutions through code.
          </p>
        </div>
      </section>

      <section className='mt-14 md:mt-28'>
        <div className='flex flex-col items-center space-y-6 md:flex-row md:space-y-0 md:space-x-12 md:justify-center'>
          <Link
            to='/about'
            className='inline-flex w-1/2 items-center justify-center shadow-brutalism-md border border-black bg-white px-8 py-4 text-base font-medium font-merriweather text-black hover:bg-gray-50 focus:outline-none focus:ring-1 focus:ring-black active:shadow-brutalism-sm active:translate-x-1 active:translate-y-1 ease-in-out duration-150 md:w-80'
          >
            About
          </Link>
          <Link
            to='/contact'
            className='inline-flex w-1/2 items-center justify-center shadow-brutalism-md border border-black bg-white px-8 py-4 text-base font-medium font-merriweather text-black hover:bg-gray-50 focus:outline-none focus:ring-1 focus:ring-black active:shadow-brutalism-sm active:translate-x-1 active:translate-y-1 ease-in-out duration-150 md:w-80'
          >
            Contact
          </Link>
        </div>
      </section>
    </>
  );
}
